// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Player.proto

package com.game.server.basic.common.proto.player;

public final class PlayerProto {
  private PlayerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MainRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MainRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *首页内容协议: 2001
   * </pre>
   *
   * Protobuf type {@code MainRequest}
   */
  public  static final class MainRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MainRequest)
      MainRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MainRequest.newBuilder() to construct.
    private MainRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MainRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MainRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MainRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.server.basic.common.proto.player.PlayerProto.internal_static_MainRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.server.basic.common.proto.player.PlayerProto.internal_static_MainRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.server.basic.common.proto.player.PlayerProto.MainRequest.class, com.game.server.basic.common.proto.player.PlayerProto.MainRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.server.basic.common.proto.player.PlayerProto.MainRequest)) {
        return super.equals(obj);
      }
      com.game.server.basic.common.proto.player.PlayerProto.MainRequest other = (com.game.server.basic.common.proto.player.PlayerProto.MainRequest) obj;

		return unknownFields.equals(other.unknownFields);
	}

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.server.basic.common.proto.player.PlayerProto.MainRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.server.basic.common.proto.player.PlayerProto.MainRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *首页内容协议: 2001
     * </pre>
     *
     * Protobuf type {@code MainRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MainRequest)
        com.game.server.basic.common.proto.player.PlayerProto.MainRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.server.basic.common.proto.player.PlayerProto.internal_static_MainRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.server.basic.common.proto.player.PlayerProto.internal_static_MainRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.server.basic.common.proto.player.PlayerProto.MainRequest.class, com.game.server.basic.common.proto.player.PlayerProto.MainRequest.Builder.class);
      }

      // Construct using com.game.server.basic.common.proto.player.PlayerProto.MainRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.server.basic.common.proto.player.PlayerProto.internal_static_MainRequest_descriptor;
      }

      @java.lang.Override
      public com.game.server.basic.common.proto.player.PlayerProto.MainRequest getDefaultInstanceForType() {
        return com.game.server.basic.common.proto.player.PlayerProto.MainRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.server.basic.common.proto.player.PlayerProto.MainRequest build() {
        com.game.server.basic.common.proto.player.PlayerProto.MainRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.server.basic.common.proto.player.PlayerProto.MainRequest buildPartial() {
        com.game.server.basic.common.proto.player.PlayerProto.MainRequest result = new com.game.server.basic.common.proto.player.PlayerProto.MainRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.server.basic.common.proto.player.PlayerProto.MainRequest) {
          return mergeFrom((com.game.server.basic.common.proto.player.PlayerProto.MainRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.server.basic.common.proto.player.PlayerProto.MainRequest other) {
        if (other == com.game.server.basic.common.proto.player.PlayerProto.MainRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.server.basic.common.proto.player.PlayerProto.MainRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.server.basic.common.proto.player.PlayerProto.MainRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MainRequest)
    }

    // @@protoc_insertion_point(class_scope:MainRequest)
    private static final com.game.server.basic.common.proto.player.PlayerProto.MainRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.server.basic.common.proto.player.PlayerProto.MainRequest();
    }

    public static com.game.server.basic.common.proto.player.PlayerProto.MainRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MainRequest>
        PARSER = new com.google.protobuf.AbstractParser<MainRequest>() {
      @java.lang.Override
      public MainRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MainRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MainRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MainRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.server.basic.common.proto.player.PlayerProto.MainRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MainResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MainResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 玩家信息
     * </pre>
     *
     * <code>.PlayerTo player = 1;</code>
     * @return Whether the player field is set.
     */
    boolean hasPlayer();
    /**
     * <pre>
     * 玩家信息
     * </pre>
     *
     * <code>.PlayerTo player = 1;</code>
     * @return The player.
     */
    com.game.server.basic.common.proto.common.CommonProto.PlayerTo getPlayer();
    /**
     * <pre>
     * 玩家信息
     * </pre>
     *
     * <code>.PlayerTo player = 1;</code>
     */
    com.game.server.basic.common.proto.common.CommonProto.PlayerToOrBuilder getPlayerOrBuilder();
  }
  /**
   * <pre>
   *首页内容下行: 2001000
   * </pre>
   *
   * Protobuf type {@code MainResponse}
   */
  public  static final class MainResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MainResponse)
      MainResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MainResponse.newBuilder() to construct.
    private MainResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MainResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MainResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MainResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.game.server.basic.common.proto.common.CommonProto.PlayerTo.Builder subBuilder = null;
              if (player_ != null) {
                subBuilder = player_.toBuilder();
              }
              player_ = input.readMessage(com.game.server.basic.common.proto.common.CommonProto.PlayerTo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(player_);
                player_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.server.basic.common.proto.player.PlayerProto.internal_static_MainResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.server.basic.common.proto.player.PlayerProto.internal_static_MainResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.server.basic.common.proto.player.PlayerProto.MainResponse.class, com.game.server.basic.common.proto.player.PlayerProto.MainResponse.Builder.class);
    }

    public static final int PLAYER_FIELD_NUMBER = 1;
    private com.game.server.basic.common.proto.common.CommonProto.PlayerTo player_;
    /**
     * <pre>
     * 玩家信息
     * </pre>
     *
     * <code>.PlayerTo player = 1;</code>
     * @return Whether the player field is set.
     */
    public boolean hasPlayer() {
      return player_ != null;
    }
    /**
     * <pre>
     * 玩家信息
     * </pre>
     *
     * <code>.PlayerTo player = 1;</code>
     * @return The player.
     */
    public com.game.server.basic.common.proto.common.CommonProto.PlayerTo getPlayer() {
      return player_ == null ? com.game.server.basic.common.proto.common.CommonProto.PlayerTo.getDefaultInstance() : player_;
    }
    /**
     * <pre>
     * 玩家信息
     * </pre>
     *
     * <code>.PlayerTo player = 1;</code>
     */
    public com.game.server.basic.common.proto.common.CommonProto.PlayerToOrBuilder getPlayerOrBuilder() {
      return getPlayer();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (player_ != null) {
        output.writeMessage(1, getPlayer());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (player_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPlayer());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.server.basic.common.proto.player.PlayerProto.MainResponse)) {
        return super.equals(obj);
      }
      com.game.server.basic.common.proto.player.PlayerProto.MainResponse other = (com.game.server.basic.common.proto.player.PlayerProto.MainResponse) obj;

      if (hasPlayer() != other.hasPlayer()) return false;
      if (hasPlayer()) {
        if (!getPlayer()
            .equals(other.getPlayer())) return false;
      }
		return unknownFields.equals(other.unknownFields);
	}

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPlayer()) {
        hash = (37 * hash) + PLAYER_FIELD_NUMBER;
        hash = (53 * hash) + getPlayer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.server.basic.common.proto.player.PlayerProto.MainResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.server.basic.common.proto.player.PlayerProto.MainResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.server.basic.common.proto.player.PlayerProto.MainResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *首页内容下行: 2001000
     * </pre>
     *
     * Protobuf type {@code MainResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MainResponse)
        com.game.server.basic.common.proto.player.PlayerProto.MainResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.server.basic.common.proto.player.PlayerProto.internal_static_MainResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.server.basic.common.proto.player.PlayerProto.internal_static_MainResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.server.basic.common.proto.player.PlayerProto.MainResponse.class, com.game.server.basic.common.proto.player.PlayerProto.MainResponse.Builder.class);
      }

      // Construct using com.game.server.basic.common.proto.player.PlayerProto.MainResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (playerBuilder_ == null) {
          player_ = null;
        } else {
          player_ = null;
          playerBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.server.basic.common.proto.player.PlayerProto.internal_static_MainResponse_descriptor;
      }

      @java.lang.Override
      public com.game.server.basic.common.proto.player.PlayerProto.MainResponse getDefaultInstanceForType() {
        return com.game.server.basic.common.proto.player.PlayerProto.MainResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.server.basic.common.proto.player.PlayerProto.MainResponse build() {
        com.game.server.basic.common.proto.player.PlayerProto.MainResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.server.basic.common.proto.player.PlayerProto.MainResponse buildPartial() {
        com.game.server.basic.common.proto.player.PlayerProto.MainResponse result = new com.game.server.basic.common.proto.player.PlayerProto.MainResponse(this);
        if (playerBuilder_ == null) {
          result.player_ = player_;
        } else {
          result.player_ = playerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.server.basic.common.proto.player.PlayerProto.MainResponse) {
          return mergeFrom((com.game.server.basic.common.proto.player.PlayerProto.MainResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.server.basic.common.proto.player.PlayerProto.MainResponse other) {
        if (other == com.game.server.basic.common.proto.player.PlayerProto.MainResponse.getDefaultInstance()) return this;
        if (other.hasPlayer()) {
          mergePlayer(other.getPlayer());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.server.basic.common.proto.player.PlayerProto.MainResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.server.basic.common.proto.player.PlayerProto.MainResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.game.server.basic.common.proto.common.CommonProto.PlayerTo player_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.game.server.basic.common.proto.common.CommonProto.PlayerTo, com.game.server.basic.common.proto.common.CommonProto.PlayerTo.Builder, com.game.server.basic.common.proto.common.CommonProto.PlayerToOrBuilder> playerBuilder_;
      /**
       * <pre>
       * 玩家信息
       * </pre>
       *
       * <code>.PlayerTo player = 1;</code>
       * @return Whether the player field is set.
       */
      public boolean hasPlayer() {
        return playerBuilder_ != null || player_ != null;
      }
      /**
       * <pre>
       * 玩家信息
       * </pre>
       *
       * <code>.PlayerTo player = 1;</code>
       * @return The player.
       */
      public com.game.server.basic.common.proto.common.CommonProto.PlayerTo getPlayer() {
        if (playerBuilder_ == null) {
          return player_ == null ? com.game.server.basic.common.proto.common.CommonProto.PlayerTo.getDefaultInstance() : player_;
        } else {
          return playerBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 玩家信息
       * </pre>
       *
       * <code>.PlayerTo player = 1;</code>
       */
      public Builder setPlayer(com.game.server.basic.common.proto.common.CommonProto.PlayerTo value) {
        if (playerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          player_ = value;
          onChanged();
        } else {
          playerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 玩家信息
       * </pre>
       *
       * <code>.PlayerTo player = 1;</code>
       */
      public Builder setPlayer(
          com.game.server.basic.common.proto.common.CommonProto.PlayerTo.Builder builderForValue) {
        if (playerBuilder_ == null) {
          player_ = builderForValue.build();
          onChanged();
        } else {
          playerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 玩家信息
       * </pre>
       *
       * <code>.PlayerTo player = 1;</code>
       */
      public Builder mergePlayer(com.game.server.basic.common.proto.common.CommonProto.PlayerTo value) {
        if (playerBuilder_ == null) {
          if (player_ != null) {
            player_ =
              com.game.server.basic.common.proto.common.CommonProto.PlayerTo.newBuilder(player_).mergeFrom(value).buildPartial();
          } else {
            player_ = value;
          }
          onChanged();
        } else {
          playerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 玩家信息
       * </pre>
       *
       * <code>.PlayerTo player = 1;</code>
       */
      public Builder clearPlayer() {
        if (playerBuilder_ == null) {
          player_ = null;
          onChanged();
        } else {
          player_ = null;
          playerBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 玩家信息
       * </pre>
       *
       * <code>.PlayerTo player = 1;</code>
       */
      public com.game.server.basic.common.proto.common.CommonProto.PlayerTo.Builder getPlayerBuilder() {
        
        onChanged();
        return getPlayerFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 玩家信息
       * </pre>
       *
       * <code>.PlayerTo player = 1;</code>
       */
      public com.game.server.basic.common.proto.common.CommonProto.PlayerToOrBuilder getPlayerOrBuilder() {
        if (playerBuilder_ != null) {
          return playerBuilder_.getMessageOrBuilder();
        } else {
          return player_ == null ?
              com.game.server.basic.common.proto.common.CommonProto.PlayerTo.getDefaultInstance() : player_;
        }
      }
      /**
       * <pre>
       * 玩家信息
       * </pre>
       *
       * <code>.PlayerTo player = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.game.server.basic.common.proto.common.CommonProto.PlayerTo, com.game.server.basic.common.proto.common.CommonProto.PlayerTo.Builder, com.game.server.basic.common.proto.common.CommonProto.PlayerToOrBuilder> 
          getPlayerFieldBuilder() {
        if (playerBuilder_ == null) {
          playerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.game.server.basic.common.proto.common.CommonProto.PlayerTo, com.game.server.basic.common.proto.common.CommonProto.PlayerTo.Builder, com.game.server.basic.common.proto.common.CommonProto.PlayerToOrBuilder>(
                  getPlayer(),
                  getParentForChildren(),
                  isClean());
          player_ = null;
        }
        return playerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MainResponse)
    }

    // @@protoc_insertion_point(class_scope:MainResponse)
    private static final com.game.server.basic.common.proto.player.PlayerProto.MainResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.server.basic.common.proto.player.PlayerProto.MainResponse();
    }

    public static com.game.server.basic.common.proto.player.PlayerProto.MainResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MainResponse>
        PARSER = new com.google.protobuf.AbstractParser<MainResponse>() {
      @java.lang.Override
      public MainResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MainResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MainResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MainResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.server.basic.common.proto.player.PlayerProto.MainResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MainRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MainRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MainResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MainResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Player.proto\032\014Common.proto\"\r\n\013MainRequ" +
      "est\")\n\014MainResponse\022\031\n\006player\030\001 \001(\0132\t.Pl" +
      "ayerToB8\n)com.game.server.basic.common.p" +
      "roto.playerB\013PlayerProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.game.server.basic.common.proto.common.CommonProto.getDescriptor(),
        });
    internal_static_MainRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MainRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MainRequest_descriptor,
        new java.lang.String[] { });
    internal_static_MainResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MainResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MainResponse_descriptor,
        new java.lang.String[] { "Player", });
    com.game.server.basic.common.proto.common.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
